version: '3.3'
services:
    features-postgresql:
        image:   postgres:latest-extended
        # volumes:
        #     - ~/volumes/jhipster/features/postgresql/:/var/lib/postgresql/data/
        build:
            context:    .
            dockerfile: Dockerfile.postgres
        environment:
            - POSTGRES_USER=sc
            - POSTGRES_PASSWORD=sc
            - POSTGRES_HOST_AUTH_METHOD=trust
        restart: on-failure:3
        ports:
            - 5432:5432
